desc "Custom build for testing"
lane :custom_build_for_testing do |options|
 #add actions here

  cocoapods

  swiftlint(
    executable: "Pods/SwiftLint/swiftlint",
    config_file: ".swiftlint.yml"
  )

  scan(
    build_for_testing: true
  )
end

desc "Custom run tests"
lane :custom_run_tests do |options|
  #add actions here

  scan( 
    test_without_building: true, 
    testplan: "FullTestPlan"
  )
end

desc "Custom build and test"
lane :custom_build_and_test do |options|
  #add actions here
  
  custom_build_for_testing
  custom_run_tests

end