name: CI
on: [push]
jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.4'
        bundler-cache: true
    - name: custom_build_and_test
      run: bundle exec fastlane custom_build_and_test
    - name: Test Success
      uses: rjstone/discord-webhook-notify@v1
      if: success()
      with:
          severity: info
          details: Test Succeeded!
          webhookUrl: ${{ secrets.DISCORD }}
    - name: Test Failure
      uses: rjstone/discord-webhook-notify@v1
      if: failure()
      with:
          severity: error
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD }}
    - name: Test Cancelled
      uses: rjstone/discord-webhook-notify@v1
      if: cancelled()
      with:
          severity: warn
          details: Test Cancelled!
          webhookUrl: ${{ secrets.DISCORD }}